[package]
name = "pingex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34.0"
socket2 = "0.5.1"
tokio = { version = "1.32.0", features = ["full"] }
byteorder = "1.3.4"